version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: devops-take-home-assignment-main-backend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: devops-take-home-assignment-main-frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
