version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
