name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init -backend-config="bucket=takehome-backend" -backend-config="key=terraform/state" -backend-config="region=us-west-2"

    - name: Check Terraform State
      id: check_state
      run: |
        if [ -z "$(terraform state list)" ]; then
          echo "State is empty, skipping destroy."
          echo "##[endgroup]"
          exit 0
        else
          echo "State is not empty, proceeding with destroy."
        fi

    - name: Terraform Destroy
      if: steps.check_state.outcome == 'success'
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}